### ISSUE TITLE
bomb info missing

### ISSUE THREAD

**Issue by OoDeLally** [doobix/csgo-c4-hue-node#2]
Thanks for the cool project!
It seems like the bomb information is missing from what I get from the game:
```

{
  provider: {
    name: 'Counter-Strike: Global Offensive',
    appid: 730,
    version: 13711,
    steamid: '..',
    timestamp: ..
  },
  map: {
    mode: 'casual',
    name: 'de_breach',
    phase: 'live',
    round: 5,
    team_ct: {
      score: 5,
      consecutive_round_losses: 0,
      timeouts_remaining: 1,
      matches_won_this_series: 0
    },
    team_t: {
      score: 0,
      consecutive_round_losses: 5,
      timeouts_remaining: 1,
      matches_won_this_series: 0
    },
    num_matches_to_win_series: 0,
    current_spectators: 0,
    souvenirs_total: 0
  },
  round: { phase: 'live' },
  player: {
    steamid: '..',
    name: '..',
    team: 'T',
    activity: 'playing',
    state: {
      health: 100,
      armor: 100,
      helmet: true,
      flashed: 0,
      smoked: 0,
      burning: 0,
      money: 1700,
      round_kills: 0,
      round_killhs: 0,
      equip_value: 2900
    },
    weapons: { weapon_0: [Object], weapon_1: [Object], weapon_2: [Object] },
    match_stats: { kills: 0, assists: 0, deaths: 0, mvps: 0, score: 0 }
  },
  auth: { token: '..' }
}                                                                                                                                      
```

As you can see, the `round` object does not contain the bomb.
Does it still work on your machine?

**Comment by doobix** [comment]
Hi @OoDeLally! I just ran the script on my computer, and it still works!

The round object has different properties depending on what is happening --

Normal: `{ phase: 'live' }`
Bomb planted: `{phase: 'live', bomb: 'planted'}`
Bomb exploded: `{phase: 'over', bomb: 'exploded', win_team: 'T'}`

**Comment by OoDeLally** [comment]
Hi @doobix , thanks for the reply, I tried again and the reason I never saw the `bomb` object is because everytime the `bomb` object actually existed, the server was crashing.
It crashes because you do not pass a callback argument to `fs.writeFile`. As you can see it really needs it: https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback, at least with node v12.5.0. You must be using an older version that may not require a callback.
